import { Crop, MarketPrice, Scheme, MarketplaceItem, WeatherData } from './types';

export const SRI_LANKAN_DISTRICTS = [
  'Colombo', 'Gampaha', 'Kalutara', 'Kandy', 'Matale', 'Nuwara Eliya',
  'Galle', 'Matara', 'Hambantota', 'Jaffna', 'Kilinochchi', 'Mannar',
  'Vavuniya', 'Mullaitivu', 'Batticaloa', 'Ampara', 'Trincomalee',
  'Kurunegala', 'Puttalam', 'Anuradhapura', 'Polonnaruwa', 'Badulla',
  'Moneragala', 'Ratnapura', 'Kegalle'
];

export const translations = {
  en: {
    title: 'SarunenaLK',
    subtitle: "Independent Smart Agricultural Operating System",
    heroHeadline: 'Cultivating the Future of Sri Lankan Agriculture with Intelligence',
    heroTagline: 'Connecting Sri Lankan farmers with real-time market prices, localized weather insights, smart tools, and AI advice. An independent smart farming initiative.',
    getStarted: 'Farmer Portal',
    learnMore: 'Explore Market Prices',
    districts: 'Districts',
    farmers: 'Active Farmers',
    schemesAccessed: 'Agricultural Schemes Accessed',
    howItWorks: 'How It Works',
    howItWorksSub: 'Our 4-step smart farming framework designed for Sri Lankan agricultural systems.',
    successStories: 'Farmer Success Stories',
    successStoriesSub: 'Real impact, real voices from the fields of Sri Lanka.',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    selectLanguage: 'Select Language',
    nationalSmartOS: 'Smart OS',
    navHome: 'Home',
    navDashboard: 'Dashboard',
    navCrops: 'My Crops',
    navWeather: 'Weather Advisory',
    navPrices: 'Market Prices',
    navSchemes: 'Schemes & Grants',
    navMarketplace: 'Farmer Market',
    navAdvisory: 'Sarunena AI Chat',
    navFertilizer: 'Fertilizer Calculator',
    navAbout: 'About & Contact',
    navGrowGuide: 'Crop Grow Guides',
    navAnimal: 'Animal Husbandry',
    navSecurity: 'Crop & Elephant Security',
    login: 'Sign In',
    register: 'Register',
    logout: 'Sign Out',
    welcomeBack: 'Ayubowan, Welcome Back!',
    weatherTitle: 'Regional Weather & Climate Advisory',
    weatherSubtitle: 'Monitored micro-climates across major dry-zone and up-country crop hubs in Sri Lanka.',
    advisoryTitlePage: 'Sarunena AI Agri-Advisor',
    advisorySubtitlePage: 'An independent AI companion trained on open Sri Lankan crop guides and local farming knowledge.',
    restrictedTitle: 'Portal Access Restricted',
    restrictedSubtitle: 'Please sign in to view your personalized farmer dashboard and manage crop sensor feeds.',
    signInNow: 'Sign In Now',
    districtsMonitored: 'Districts Monitored',
    suiteTitle: 'Comprehensive Smart Farming Suite',
    suiteSubtitle: 'Everything a modern Sri Lankan farmer needs, integrated in one unified platform.',
    card1Title: 'Real-Time Crop Health',
    card1Desc: 'Log crop variants, check soil moisture indices, evaluate pH balances, and monitor growing cycles with active sensor alerts.',
    card1Action: 'Go to Crops Registry',
    card2Title: 'Daily HARTI Market Prices',
    card2Desc: 'Daily wholesale rate index directly mapped from major distribution centers. Compare rates and secure maximum profits.',
    card2Action: 'Explore Prices',
    card3Title: 'Regional Weather Advisories',
    card3Desc: 'Localized forecasts and monsoonal advice tailored to Sri Lankan cultivation zones (Wet, Dry, and Intermediate).',
    card3Action: 'Open Weather advisory',
    card4Title: 'Agricultural Initiatives & Grants',
    card4Desc: 'Browse and apply for organic compost, high-yield seeds, and smart micro-irrigation equipment grants.',
    card4Action: 'See Initiatives',
    card5Title: 'Farmer Direct Marketplace',
    card5Desc: 'Buy seeds and organic manures, list your upcoming produce directly for bulk buyers, or rent out tractors in your district.',
    card5Action: 'Enter Marketplace',
    card6Title: 'NPK Fertilizer Calculator',
    card6Desc: 'Compute the exact required splits of Urea, TSP, and MOP required for your acreage. Follow standard crop guidelines.',
    card6Action: 'Calculate Soil Needs',
    step1Title: 'Govi Sign In',
    step1Desc: 'Sign in with your email or Govi ID. Set your cultivation district.',
    step2Title: 'Record Your Crops',
    step2Desc: 'Log active paddies, vegetables, or spices to track growth stages.',
    step3Title: 'Apply for Grants',
    step3Desc: 'Review eligibility tags and apply for compost or smart farming equipment.',
    step4Title: 'Leverage AI Advisories',
    step4Desc: 'Interact with Sarunena AI to diagnose thrips, pests, or calculate NPK ratios.',
    footerDesc: 'Empowering local farmers across Sri Lanka with real-time agronomic data, transparent market prices, and quick access to independent agricultural schemes.',
    govCertified: 'Independent Smart Platform',
    govPortals: 'External Resources',
    minAgri: 'Ministry of Agriculture (External)',
    deptAgri: 'Dept of Agriculture (External)',
    metDept: 'Meteorology Department (External)',
    hartiCrop: 'HARTI Crop Prices',
    nationalAgriSec: 'SarunenaLK Independent Farm Project',
    goviMandiraya: 'Colombo, Sri Lanka',
    hotlineLabel: '1920 (Agri-Advisory Hotline)',
    allRightsReserved: 'SarunenaLK Independent Smart Farm Project.',
    ministryCopyright: 'Designed, Developed, and Managed independently.',
    dbPortal: 'Portal',
    dbRepresenting: 'Representing',
    dbDistrict: 'District',
    dbFarmingId: 'Sarunena Smart Farming ID:',
    dbFarmingSeason: 'Farming Season:',
    dbYalaCycle: 'Yala 2026 Cycle',
    dbMonitoredCrops: 'Monitored Crops',
    dbManageCrops: 'Manage Crops',
    dbTotalArea: 'Total Area',
    dbAcrossPlots: 'Across all plots',
    dbSensoryAlerts: 'Sensory Alerts',
    dbCheckCrops: 'Check crops immediately',
    dbSubsidiesPayout: 'Subsidies Payout',
    dbBrowseSchemes: 'Browse Schemes',
    dbCropHealthSummary: 'Cultivated Crop Health Summary',
    dbOpenCropRegistry: 'Open Crop Registry',
    dbProgress: 'Progress',
    dbBulletin: 'SarunenaLK Agricultural Bulletin',
    dbBulletinCompiled: 'Information compiled independently by SarunenaLK',
    dbActiveFarmers: 'Active Farmers Network',
    dbFarmersDesc: 'Registering new farm profiles adds landholders instantly to this directory. Currently synced in local cluster.',
    dbAcres: 'Acres'
  },
  si: {
    title: 'සරුනැණ LK',
    subtitle: 'ස්වාධීන ස්මාර්ට් කෘෂිකාර්මික මෙහෙයුම් පද්ධතිය',
    heroHeadline: 'බුද්ධිමත් තාක්ෂණයෙන් ශ්‍රී ලාංකීය කෘෂිකර්මාන්තයේ අනාගතය සරු කරමු',
    heroTagline: 'ශ්‍රී ලංකාවේ ගොවීන් තථ්‍ය කාලීන වෙළඳපල මිල ගණන්, කාලගුණ අනාවැකි, ස්මාර්ට් උපකරණ සහ කෘතිම බුද්ධි උපදෙස් සමඟ සම්බන්ධ කෙරෙන ස්වාධීන මුලපිරීමකි.',
    getStarted: 'ගොවි ද්වාරය',
    learnMore: 'වෙළඳපල මිල ගණන්',
    districts: 'දිස්ත්‍රික්ක',
    farmers: 'ක්‍රියාකාරී ගොවීන්',
    schemesAccessed: 'සම්බන්ධිත කෘෂි ව්‍යාපෘති',
    howItWorks: 'ක්‍රියාකාරීත්වය',
    howItWorksSub: 'ශ්‍රී ලංකාවේ කෘෂිකාර්මික පද්ධති සඳහා නිර්මාණය කර ඇති අපගේ පියවර 4ක ස්මාර්ට් ගොවිතැන් රාමුව.',
    successStories: 'සාර්ථක කථා',
    successStoriesSub: 'ශ්‍රී ලාංකීය ගොවිබිම්වලින් ඇසෙන සැබෑ හඬ සහ සැබෑ වෙනස.',
    quickLinks: 'ක්ෂණික සබැඳි',
    contactUs: 'අප අමතන්න',
    selectLanguage: 'භාෂාව',
    nationalSmartOS: 'ස්මාර්ට් පද්ධතිය',
    navHome: 'ප්‍රධාන පිටුව',
    navDashboard: 'පාලක පුවරුව',
    navCrops: 'මගේ වගාවන්',
    navWeather: 'කාලගුණ උපදෙස්',
    navPrices: 'වෙළඳපල මිල',
    navSchemes: 'ව්‍යාපෘති සහ ආධාර',
    navMarketplace: 'ගොවි පොළ',
    navAdvisory: 'සරුනැණ AI',
    navFertilizer: 'පොහොර කැල්කියුලේටරය',
    navAbout: 'විස්තර සහ සම්බන්ධතා',
    navGrowGuide: 'බෝග වගා උපදෙස්',
    navAnimal: 'සත්ව පාලනය',
    navSecurity: 'බෝග සහ අලි ආරක්ෂාව',
    login: 'ඇතුල් වන්න',
    register: 'ලියාපදිංචි වන්න',
    logout: 'නික්ම යන්න',
    welcomeBack: 'ආයුබෝවන්, නැවත සාදරයෙන් පිළිගනිමු!',
    weatherTitle: 'ප්‍රාදේශීය කාලගුණ සහ දේශගුණ උපදේශනය',
    weatherSubtitle: 'ශ්‍රී ලංකාවේ ප්‍රධාන වියළි කලාපීය සහ කඳුකර බෝග වගා කලාපයන්හි ක්ෂුද්‍ර දේශගුණ තත්ත්වයන්.',
    advisoryTitlePage: 'සරුනැණ AI කෘෂි උපදෙස්',
    advisorySubtitlePage: 'ශ්‍රී ලංකාවේ බෝග වගා මාර්ගෝපදේශ සහ දේශීය ගොවි දැනুම මත පුහුණු කරන ලද ස්වාධීන කෘතිම බුද්ධි සහායකයෙකි.',
    restrictedTitle: 'ප්‍රවේශය සීමා කර ඇත',
    restrictedSubtitle: 'ඔබේ පුද්ගලීකරණය කළ ගොවි පාලක පුවරුව නැරඹීමට සහ බෝග සංවේදක කළමනාකරණය කිරීමට කරුණාකර ඇතුල් වන්න.',
    signInNow: 'දැන් ඇතුල් වන්න',
    districtsMonitored: 'නිරීක්ෂණය කරන දිස්ත්‍රික්ක',
    suiteTitle: 'විස්තීර්ණ ස්මාර්ට් ගොවිතැන් කට්ටලය',
    suiteSubtitle: 'නූතන ශ්‍රී ලාංකීය ගොවියෙකුට අවශ්‍ය සියලුම මෙවලම් එක් පද්ධතියක් තුළ ඒකාබද්ධ කර ඇත.',
    card1Title: 'තථ්‍ය කාලීන බෝග සෞඛ්‍යය',
    card1Desc: 'බෝග ප්‍රභේද සටහන් කරන්න, පසේ තෙතමනය දර්ශක පරීක්ෂා කරන්න, pH අගය මැන බලන්න, සහ ක්‍රියාකාරී සංවේදක ඇඟවීම් සමඟ වර්ධන චක්‍ර නිරීක්ෂණය කරන්න.',
    card1Action: 'බෝග ලේඛනයට යන්න',
    card2Title: 'දිනපතා හාර්ටි (HARTI) වෙළඳපල මිල ගණන්',
    card2Desc: 'ප්‍රධාන බෙදාහැරීමේ මධ්‍යස්ථානවලින් සෘජුවම ලබාගන්නා දෛනික තොග මිල දර්ශකය. මිල ගණන් සසඳා උපරිම ලාභ ලබා ගන්න.',
    card2Action: 'මිල ගණන් ගවේෂණය කරන්න',
    card3Title: 'ප්‍රාදේශීය කාලගුණ උපදෙස්',
    card3Desc: 'ශ්‍රී ලංකාවේ වගා කලාපවලට (තෙත්, වියළි සහ අතරමැදි) ගැළපෙන පරිදි සකස් කරන ලද ප්‍රාදේශීය අනාවැකි සහ මෝසම් උපදෙස්.',
    card3Action: 'කාලගුණ උපදෙස් බලන්න',
    card4Title: 'කෘෂිකාර්මික මුලපිරීම් සහ ආධාර',
    card4Desc: 'කාබනික පොහොර, උසස් තත්ත්වයේ බීජ සහ ස්මාර්ට් බිංදු ජල සම්පාදන උපකරණ ප්‍රතිපාදන පිළිබඳ විස්තර ගවේෂණය කරන්න.',
    card4Action: 'ප්‍රතිලාභ බලන්න',
    card5Title: 'ගොවීන්ගේ සෘජු වෙළඳපොළ',
    card5Desc: 'බීජ සහ කාබනික පොහොර මිලදී ගන්න, ඔබේ අස්වැන්න තොග ගැනුම්කරුවන් සඳහා සෘජුවම ලැයිස්තුගත කරන්න, නැතහොත් ඔබේ දිස්ත්‍රික්කයේ ට්‍රැක්ටර් කුලියට දෙන්න.',
    card5Action: 'වෙළඳපොළට ඇතුළු වන්න',
    card6Title: 'NPK පොහොර ගණකය',
    card6Desc: 'ඔබේ වගා භූමියට අවශ්‍ය යූරියා, TSP සහ MOP ප්‍රමාණයන් නිවැරදිව ගණනය කරන්න. සම්මත බෝග උපදෙස් අනුගමනය කරන්න.',
    card6Action: 'පස් අවශ්‍යතා ගණනය කරන්න',
    step1Title: 'ගොවි ඇතුල් වීම',
    step1Desc: 'ඔබගේ විද්‍යුත් තැපෑල හෝ ගොවි හැඳුනුම්පත මඟින් ඇතුල් වන්න. ඔබගේ වගා දිස්ත්‍රික්කය සකසන්න.',
    step2Title: 'වගාවන් ලියාපදිංචි කරන්න',
    step2Desc: 'වර්ධන අවධීන් නිරීක්ෂණය කිරීම සඳහා සක්‍රීය වී, එළවළු හෝ කුළුබඩු වගාවන් ඇතුළත් කරන්න.',
    step3Title: 'ආධාර සඳහා අයදුම් කරන්න',
    step3Desc: 'සුදුසුකම් පරීක්ෂා කර කාබනික පොහොර හෝ ස්මාර්ට් කෘෂි උපකරණ සඳහා අයදුම් කරන්න.',
    step4Title: 'කෘතිම බුද්ධි (AI) උපදෙස් ලබාගන්න',
    step4Desc: 'වගා රෝග, පළිබෝධකයන් හඳුනා ගැනීමට හෝ පසේ NPK අවශ්‍යතා ගණනය කිරීමට සරුනැණ AI සමඟ සම්බන්ධ වන්න.',
    footerDesc: 'තථ්‍ය කාලීන කෘෂිකාර්මික දත්ත, විනිවිදභාවයෙන් යුත් වෙළඳපල මිල ගණන් සහ ස්වාධීන කෘෂිකාර්මික ව්‍යාපෘති පහසුවෙන් ලබා ගැනීමේ පහසුකම මඟින් ශ්‍රී ලංකාව පුරා සිටින දේශීය ගොවීන් සවිබල ගැන්වීම.',
    govCertified: 'ස්වාධීන ස්මාර්ට් වේදිකාව',
    govPortals: 'බාහිර මූලාශ්‍ර',
    minAgri: 'කෘෂිකර්ම අමාත්‍යාංශය (බාහිර)',
    deptAgri: 'කෘෂිකර්ම දෙපාර්තමේන්තුව (බාහිර)',
    metDept: 'කාලගුණ විද්‍යා දෙපාර්තමේන්තුව (බාහිර)',
    hartiCrop: 'හාර්ටි (HARTI) බෝග මිල ගණන්',
    nationalAgriSec: 'සරුනැණLK ස්වාධීන කෘෂි ව්‍යාපෘතිය',
    goviMandiraya: 'කොළඹ, ශ්‍රී ලංකාව',
    hotlineLabel: '1920 (කෘෂි උපදෙස් ක්ෂණික ඇමතුම් අංකය)',
    allRightsReserved: 'සරුනැණLK ස්වාධීන ස්මාර්ට් ගොවි ව්‍යාපෘතිය.',
    ministryCopyright: 'සම්පූර්ණයෙන්ම ස්වාධීනව සැලසුම් කර, සංවර්ධනය කර පවත්වාගෙන යනු ලැබේ.',
    dbPortal: 'ද්වාරය',
    dbRepresenting: 'නියෝජනය කරන්නේ',
    dbDistrict: 'දිස්ත්‍රික්කය',
    dbFarmingId: 'සරුනැණ ස්මාර්ට් ගොවි හැඳුනුම්පත:',
    dbFarmingSeason: 'වගා කන්නය:',
    dbYalaCycle: 'යල 2026 කන්නය',
    dbMonitoredCrops: 'නිරීක්ෂිත බෝග',
    dbManageCrops: 'බෝග කළමනාකරණය',
    dbTotalArea: 'මුළු ඉඩම් ප්‍රමාණය',
    dbAcrossPlots: 'සියලුම බිම් කොටස් පුරා',
    dbSensoryAlerts: 'සංවේදක අනතුරු ඇඟවීම්',
    dbCheckCrops: 'වහාම වගාවන් පරීක්ෂා කරන්න',
    dbSubsidiesPayout: 'ලැබුණු සහනාධාර',
    dbBrowseSchemes: 'ව්‍යාපෘති ගවේෂණය',
    dbCropHealthSummary: 'වගා කරන ලද බෝගවල සාරාංශය',
    dbOpenCropRegistry: 'බෝග ලේඛනය විවෘත කරන්න',
    dbProgress: 'ප්‍රගතිය',
    dbBulletin: 'සරුනැණLK කෘෂිකාර්මික පුවත්පත',
    dbBulletinCompiled: 'තොරතුරු සරුනැණLK විසින් ස්වාධීනව සකස් කරන ලදී',
    dbActiveFarmers: 'ක්‍රියාකාරී ගොවීන්ගේ ජාලය',
    dbFarmersDesc: 'නව ගොවි ගිණුම් ලියාපදිංචි කිරීමෙන් ගොවීන් මෙම නාමාවලියට එකතු වේ. දැනට දේශීයව සමමුහුර්ත කර ඇත.',
    dbAcres: 'අක්කර'
  },
  ta: {
    title: 'சருனேன LK',
    subtitle: 'சுயாதீன ஸ்மார்ட் விவசாய இயக்க முறைமை',
    heroHeadline: 'புத்திசாலித்தனமான தொழில்நுட்பத்துடன் இலங்கை விவசாயத்தின் எதிர்காலத்தை வளமாக்குவோம்',
    heroTagline: 'விவசாயிகளுக்கு நிகழ்நேர சந்தை விலைகள், வானிலை முன்னறிவிப்புகள், ஸ்மார்ட் உபகரணங்கள் மற்றும் AI ஆலோசனைகளை வழங்கும் சுயாதீன முயற்சி.',
    getStarted: 'விவசாயி போர்டல்',
    learnMore: 'சந்தை விலைகள்',
    districts: 'மாவட்டங்கள்',
    farmers: 'செயலில் உள்ள விவசாயிகள்',
    schemesAccessed: 'இணைக்கப்பட்ட விவசாய திட்டங்கள்',
    howItWorks: 'செயல்முறை',
    howItWorksSub: 'இலங்கை விவசாய அமைப்புகளுக்காக வடிவமைக்கப்பட்ட எமது 4-படி ஸ்மார்ட் விவசாய கட்டமைப்பு.',
    successStories: 'வெற்றி கதைகள்',
    successStoriesSub: 'இலங்கை விவசாய நிலங்களின் உண்மையான குரல்களும் மாற்றங்களும்.',
    quickLinks: 'விரைவான இணைப்புகள்',
    contactUs: 'எங்களைத் தொடர்பு கொள்ள',
    selectLanguage: 'மொழி',
    nationalSmartOS: 'ஸ்மார்ட் தளம்',
    navHome: 'முகப்பு',
    navDashboard: 'டாஷ்போர்டு',
    navCrops: 'எனது பயிர்கள்',
    navWeather: 'வானிலை ஆலோசனை',
    navPrices: 'சந்தை விலைகள்',
    navSchemes: 'திட்டங்கள் & மானியங்கள்',
    navMarketplace: 'விவசாய சந்தை',
    navAdvisory: 'சருனேன AI அரட்டை',
    navFertilizer: 'உர கால்குலேட்டர்',
    navAbout: 'பற்றி & தொடர்பு',
    navGrowGuide: 'பயிர் வளர்ப்பு வழிகாட்டிகள்',
    navAnimal: 'கால்நடை வளர்ப்பு',
    navSecurity: 'பயிர் மற்றும் யானை பாதுகாப்பு',
    login: 'உள்நுழையவும்',
    register: 'பதிவு செய்யவும்',
    logout: 'வெளியேறவும்',
    welcomeBack: 'ஆயுபோவன், மீண்டும் வருக!',
    weatherTitle: 'பிராந்திய வானிலை மற்றும் காலநிலை ஆலோசனை',
    weatherSubtitle: 'இலங்கையின் முக்கிய வறண்ட மண்டல மற்றும் மலைநாட்டு பயிர் மையங்களின் நுண் காலநிலை நிலைமைகள்.',
    advisoryTitlePage: 'சருனேன AI விவசாய ஆலோசகர்',
    advisorySubtitlePage: 'திறந்த இலங்கை பயிர் வழிகாட்டிகள் மற்றும் உள்ளூர் விவசாய அறிவின் அடிப்படையில் பயிற்சி பெற்ற ஒரு சுயாதீன டிஜிட்டல் உதவியாளர்.',
    restrictedTitle: 'அணுகல் தடைசெய்யப்பட்டுள்ளது',
    restrictedSubtitle: 'உங்கள் தனிப்பயனாக்கப்பட்ட விவசாயி டாஷ்போர்டைப் பார்க்கவும் பயிர் சென்சார்களை நிர்வகிக்கவும் தயவுசெய்து உள்நுழையவும்.',
    signInNow: 'இப்போது உள்நுழைக',
    districtsMonitored: 'கண்காணிக்கப்படும் மாவட்டங்கள்',
    suiteTitle: 'விரிவான ஸ்மார்ட் விவசாய தொகுப்பு',
    suiteSubtitle: 'ஒரு நவீன இலங்கை விவசாயிக்குத் தேவையான அனைத்தும் ஒரே தளத்தில் ஒருங்கிணைக்கப்பட்டுள்ளன.',
    card1Title: 'நிகழ்நேர பயிர் ஆரோக்கியம்',
    card1Desc: 'பயிர் வகைகளைப் பதிவு செய்யவும், மண் ஈரப்பதக் குறியீடுகளைச் சரிபார்க்கவும், pH அளவை மதிப்பிடவும், மற்றும் சென்சார் விழிப்பூட்டல்களுடன் வளரும் சுழற்சிகளைக் கண்காணிக்கவும்.',
    card1Action: 'பயிர் பதிவேட்டிற்குச் செல்லவும்',
    card2Title: 'தினசரி HARTI சந்தை விலைகள்',
    card2Desc: 'முக்கிய விநியோக மையங்களிலிருந்து நேரடியாகப் பெறப்படும் தினசரி மொத்த விலை குறியீடு. விலைகளை ஒப்பிட்டு அதிகபட்ச இலாபத்தைப் பெறுங்கள்.',
    card2Action: 'ஒப்பிட்டு விலைகளை ஆராயுங்கள்',
    card3Title: 'பிராந்திய வானிலை ஆலோசனைகள்',
    card3Desc: 'இலங்கையின் பயிர்ச்செய்கை மண்டலங்களுக்கு (ஈரமான, உலர் மற்றும் இடைநிலை) ஏற்றவாறு வடிவமைக்கப்பட்ட உள்ளூர் வானிலை முன்னறிவிப்புகள் மற்றும் பருவமழை ஆலோசனைகள்.',
    card3Action: 'வானிலை ஆலோசனையைத் திறக்கவும்',
    card4Title: 'விவசாயத் திட்டங்கள் & மானியம்',
    card4Desc: 'தேசிய உரம், உயர்தர விதைகள் மற்றும் ஸ்மார்ட் சொட்டு நீர் பாசன உபகரண உதவித் திட்டங்களின் விவரங்களை ஆராயுங்கள்.',
    card4Action: 'திட்டங்களைப் பார்க்கவும்',
    card5Title: 'விவசாயி நேரடி சந்தை',
    card5Desc: 'விதைகள் மற்றும் கரிம உரங்களை வாங்கவும், உங்கள் விளைச்சலை மொத்த வாங்குபவர்களுக்கு நேரடியாக பட்டியலிடவும், அல்லது உங்கள் மாவட்டத்தில் டிராக்டர்களை வாடகைக்கு விடவும்.',
    card5Action: 'சந்தையில் நுழையுங்கள்',
    card6Title: 'NPK உர கால்குலேட்டர்',
    card6Desc: 'மண் தேவைகளைக் கணக்கிடுங்கள்',
    card6Action: 'மண் தேவைகளைக் கணக்கிடுங்கள்',
    step1Title: 'விவசாயி போர்டல் உள்நுழையவும்',
    step1Desc: 'மின்னஞ்சல் அல்லது விவசாயி ஐடி மூலம் உள்நுழையவும். சாகுபடி மாவட்டத்தை அமைக்கவும்.',
    step2Title: 'பயிர்களைப் பதிவு செய்யவும்',
    step2Desc: 'வளர்ச்சி நிலைகளைக் கண்காணிக்க நெல், காயறிகள் அல்லது மசாலாப் பயிர்களைப் பதிவு செய்யவும்.',
    step3Title: 'மானியங்களுக்கு விண்ணப்பிக்கவும்',
    step3Desc: 'தகுதி வரம்புகளை மதிப்பாய்வு செய்து இயற்கை உரங்கள் அல்லது ஸ்மார்ட் விவசாய உபகரணங்களுக்கு விண்ணப்பிக்கவும்.',
    step4Title: 'AI ஆலோசனைகளைப் பெறுங்கள்',
    step4Desc: 'பூச்சிகளைக் கண்டறிய அல்லது மண் NPK தேவைகளைக் கணக்கிட சருனேன AI உடன் உரையாடுங்கள்.',
    footerDesc: 'நிகழ்நேர விவசாயத் தரவு, வெளிப்படையான சந்தை விலைகள் மற்றும் சுயாதீன விவசாய திட்டங்களை எளிதாக அணுகுவதன் மூலம் இலங்கையிலுள்ள உள்ளூர் விவசாயிகளுக்கு அதிகாரம் அளித்தல்.',
    govCertified: 'சுயாதீன ஸ்மார்ட் தளம்',
    govPortals: 'வெளிப்புற ஆதாரங்கள்',
    minAgri: 'விவசாய அமைச்சு (வெளிப்புற)',
    deptAgri: 'விவசாயத் திணைக்களம் (வெளிப்புற)',
    metDept: 'வளிமண்டலவியல் திணைக்களம் (வெளிப்புற)',
    hartiCrop: 'HARTI பயிர் விலைகள்',
    nationalAgriSec: 'சருனேனLK சுயாதீன விவசாயத் திட்டம்',
    goviMandiraya: 'கொழும்பு, இலங்கை',
    hotlineLabel: '1920 (விவசாய ஆலோசனை உதவி எண்)',
    allRightsReserved: 'சருனேனLK சுயாதீன ஸ்மார்ட் பண்ணை திட்டம்.',
    ministryCopyright: 'முழுமையாக சுயாதீனமாக வடிவமைக்கப்பட்டு, உருவாக்கப்பட்டு நிர்வகிக்கப்படுகிறது.',
    dbPortal: 'போர்டல்',
    dbRepresenting: 'பிரதிநிதித்துவப்படுத்துகிறது',
    dbDistrict: 'மாவட்டம்',
    dbFarmingId: 'சருனேன ஸ்மார்ட் விவசாய ஐடி:',
    dbFarmingSeason: 'விவசாய பருவம்:',
    dbYalaCycle: 'யால 2026 சுழற்சி',
    dbMonitoredCrops: 'கண்காணிக்கப்படும் பயிர்கள்',
    dbManageCrops: 'பயிர்களை நிர்வகிக்கவும்',
    dbTotalArea: 'மொத்த பரப்பளவு',
    dbAcrossPlots: 'அனைத்து நிலப்பரப்புகளிலும்',
    dbSensoryAlerts: 'சென்சார் எச்சரிக்கைகள்',
    dbCheckCrops: 'பயிர்களை உடனே சரிபார்க்கவும்',
    dbSubsidiesPayout: 'மானியங்கள் கொடுப்பனவு',
    dbBrowseSchemes: 'திட்டங்களை உலாவவும்',
    dbCropHealthSummary: 'பயிரிடப்பட்ட பயிர் ஆரோக்கிய சுருக்கம்',
    dbOpenCropRegistry: 'பயிர் பதிவேட்டைத் திறக்கவும்',
    dbProgress: 'முன்னேற்றம்',
    dbBulletin: 'சருனேனLK விவசாய புல்லட்டின்',
    dbBulletinCompiled: 'தகவல்கள் சருனேனLK மூலம் சுயாதீனமாக தொகுக்கப்பட்டன',
    dbActiveFarmers: 'செயலில் உள்ள விவசாயிகள் நெட்வொர்க்',
    dbFarmersDesc: 'புதிய பண்ணை சுயவிவரங்களை பதிவு செய்வதன் மூலம் விவசாயிகள் உடனடியாக இந்த கோப்பகத்தில் சேர்க்கப்படுவார்கள். தற்போது உள்ளூரில் ஒத்திசைக்கப்பட்டுள்ளது.',
    dbAcres: 'ஏக்கர்'
  }
};

export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'scheme-1',
    title: {
      en: 'SarunenaLK Organic Fertilizer & Compost Initiative',
      si: 'සරුනැණ LK කාබනික පොහොර සහ කොම්පෝස්ට් සහනාධාරය',
      ta: 'சருனேன எல்கே இயற்கை உரம் & மட்கிய உரம் மானியம்'
    },
    description: {
      en: 'Provides free organic fertilizer packs and a cash grant of Rs. 15,000 per acre to promote sustainable eco-friendly paddy farming in Sri Lanka.',
      si: 'ශ්‍රී ලංකාව තුළ තිරසාර පරිසර හිතකාමී වී වගාව ප්‍රවර්ධනය කිරීම සඳහා නොමිලේ කාබනික පොහොර ඇසුරුම් සහ අක්කරයකට රු. 15,000 ක මුදල් ආධාර ලබා දීම.',
      ta: 'இலங்கையில் நிலையான சூழல் நட்பு நெல் விவசாயத்தை ஊக்குவிப்பதற்காக இலவச இயற்கை உரப் பொதிகள் மற்றும் ஏக்கருக்கு ரூ. 15,000 ரொக்க மானியம் வழங்குகிறது.'
    },
    subsidyPercentage: 85,
    authority: {
      en: 'SarunenaLK Community Farm Initiative',
      si: 'සරුනැණ LK ප්‍රජා ගොවි පදනම',
      ta: 'சருனேன எல்கே சமூக விவசாய முயற்சி'
    },
    eligibility: ['Active Paddy Farmers', 'Minimum land size 0.5 Acres', 'Maximum land size 5 Acres'],
    deadline: '2026-07-20',
    category: 'Fertilizer',
    status: 'Open'
  },
  {
    id: 'scheme-2',
    title: {
      en: 'Agri-Tech Smart Micro-Irrigation Grant',
      si: 'ස්මාර්ට් ක්ෂුද්‍ර ජල සම්පාදන තාක්ෂණික ප්‍රතිපාදන',
      ta: 'விவசாய தொழில்நுட்ப ஸ்மார்ட் நுண் பாசன மானியம்'
    },
    description: {
      en: 'Covers major purchase costs of drip and sprinkler irrigation equipment for farmers in dry-zone districts (Anuradhapura, Polonnaruwa, Jaffna).',
      si: 'වියළි කලාපීය දිස්ත්‍රික්කවල (අනුරාධපුරය, පොළොන්නරුව, යාපනය) ගොවීන් සඳහා බිංදු සහ විදින ජල සම්පාදන උපකරණ මිලදී ගැනීමේ පිරිවැයෙන් වැඩි ප්‍රමාණයක් පියවයි.',
      ta: 'வறண்ட மண்டல மாவட்டங்களில் (அனுராதபுரம், பொலன்னறுவை, யாழ்ப்பாணம்) உள்ள விவசாயிகளுக்கு சொட்டுநீர் மற்றும் தெளிப்பு நீர் பாசன உபகரணங்களை வாங்குவதற்கான முக்கிய செலவுகளை உள்ளடக்கியது.'
    },
    subsidyPercentage: 70,
    authority: {
      en: 'SarunenaLK Technology Partners',
      si: 'සරුනැණ LK තාක්ෂණික හවුල්කරුවන්',
      ta: 'சருனேன எல்கே தொழில்நுட்ப பங்காளர்கள்'
    },
    eligibility: ['Dry zone cultivation', 'Active farm records in SarunenaLK', 'Well water or reliable source access'],
    deadline: '2026-08-05',
    category: 'Equipment',
    status: 'Open'
  },
  {
    id: 'scheme-3',
    title: {
      en: 'Export Crop Modernization Financial Facility',
      si: 'අපනයන බෝග නවීකරණ මූල්‍ය ආධාර',
      ta: 'ஏற்றுமதி பயிர் நவீனமயமாக்கல் நிதி வசதி'
    },
    description: {
      en: 'Low-interest credit facility (4.5% p.a.) coupled with free processing technology training for Cinnamon, Pepper, and Cardamom growers.',
      si: 'කුරුඳු, ගම්මිරිස් සහ කරදමුංගු වගා කරන්නන් සඳහා නොමිලේ සැකසුම් තාක්ෂණික පුහුණුව සමඟ අඩු පොලී ණය පහසුකම් (වසරකට 4.5%).',
      ta: 'இலங்கப்பட்டை, மிளகு மற்றும் ஏலக்காய் பயிரிடுபவர்களுக்கு இலவச பதப்படுத்தும் தொழில்நுட்ப பயிற்சியுடன் கூடிய குறைந்த வட்டி கடன் வசதி (ஆண்டுக்கு 4.5%).'
    },
    subsidyPercentage: 50,
    authority: {
      en: 'SarunenaLK Agronomy Network',
      si: 'සරුනැණ LK කෘෂි විද්‍යා ජාලය',
      ta: 'சருனேன எல்கே வேளாண்மை நெட்வொர்க்'
    },
    eligibility: ['Export agriculture crop growers', 'Cinnamon, Pepper, Cardamom, or Clove plantations', 'Certified land registry ownership'],
    deadline: '2026-08-30',
    category: 'Loan',
    status: 'Open'
  },
  {
    id: 'scheme-4',
    title: {
      en: 'Yala Season Seed Paddy Distribution',
      si: 'යල කන්නයේ බීජ වී බෙදා හැරීම',
      ta: 'யால பருவ விதை நெல் விநியோகம்'
    },
    description: {
      en: 'Distribution of high-yielding, certified seed paddy varieties (BG series) resistant to common regional blights and water stress.',
      si: 'කලාපීය කෘමි හානි සහ ජල හිඟයට ඔරොත්තු දෙන ඉහළ අස්වැන්නක් සහිත සහතික කළ බීජ වී ප්‍රභේද (BG කාණ්ඩය) බෙදා හැරීම.',
      ta: 'பொதுவான பிராந்திய நோய்கள் மற்றும் நீர் அழுத்தத்திற்கு எதிர்ப்புத் தெரிவிக்கும் அதிக மகசூல் தரும், சான்றளிக்கப்பட்ட விதை நெல் ரகங்களை (BG தொடர்) விநியோகித்தல்.'
    },
    subsidyPercentage: 100,
    authority: {
      en: 'Batalagoda Seed Partners & SarunenaLK',
      si: 'බත්ලගොඩ බීජ හවුල්කරුවන් සහ සරුනැණ LK',
      ta: 'பத்தலகொட விதை பங்காளர்கள் & சருனேன எல்கே'
    },
    eligibility: ['Paddy land ownership registered under SarunenaLK', 'Verification of field preparation status'],
    deadline: '2026-07-15',
    category: 'Seed',
    status: 'Applied'
  }
];
export const MOCK_CROPS: Crop[] = [
  {
    id: 'crop-1',
    name: { en: 'Samba Paddy', si: 'සම්බා වී', ta: 'சம்பா நெல்' },
    category: 'Paddy',
    healthStatus: 'Excellent',
    growthStage: 'Flowering',
    progress: 75,
    plantedDate: '2026-04-10',
    expectedHarvest: '2026-08-15',
    areaAcres: 2.5,
    moisture: 68,
    soilPH: 6.2,
    alerts: []
  },
  {
    id: 'crop-2',
    name: { en: 'Red Onions', si: 'රතු ළූණු', ta: 'சிவப்பு வெங்காயம்' },
    category: 'Vegetable',
    healthStatus: 'Good',
    growthStage: 'Vegetative',
    progress: 45,
    plantedDate: '2026-05-12',
    expectedHarvest: '2026-08-01',
    areaAcres: 1.2,
    moisture: 52,
    soilPH: 6.8,
    alerts: ['Slight moisture drop detected. Schedule evening watering.']
  },
  {
    id: 'crop-3',
    name: { en: 'Carrots', si: 'කැරට්', ta: 'கேரட்' },
    category: 'Vegetable',
    healthStatus: 'Fair',
    growthStage: 'Seeding',
    progress: 20,
    plantedDate: '2026-06-01',
    expectedHarvest: '2026-09-10',
    areaAcres: 0.8,
    moisture: 80,
    soilPH: 6.0,
    alerts: ['Damping-off risk due to high cloud cover. Keep drainage open.']
  },
  {
    id: 'crop-4',
    name: { en: 'Ceylon Cinnamon', si: 'කුරුඳු', ta: 'இலவங்கப்பட்டை' },
    category: 'Export',
    healthStatus: 'Excellent',
    growthStage: 'Harvesting',
    progress: 95,
    plantedDate: '2024-03-15',
    expectedHarvest: '2026-07-05',
    areaAcres: 4.0,
    moisture: 45,
    soilPH: 5.5,
    alerts: []
  },
  {
    id: 'crop-5',
    name: { en: 'Green Chillies', si: 'අමු මිරිස්', ta: 'பச்சை மிளகாய்' },
    category: 'Vegetable',
    healthStatus: 'At Risk',
    growthStage: 'Flowering',
    progress: 60,
    plantedDate: '2026-04-28',
    expectedHarvest: '2026-07-25',
    areaAcres: 0.5,
    moisture: 35,
    soilPH: 6.4,
    alerts: [
      'Pest infestation risk (Thrips detected nearby). Spray neem oil extract.',
      'Critical soil moisture stress. Please irrigate immediately!'
    ]
  }
];

export const MOCK_MARKET_PRICES: MarketPrice[] = [
  {
    id: 'price-1',
    cropName: { en: 'Keeri Samba Paddy', si: 'කීරි සම්බා වී', ta: 'கீரி சம்பா நெல்' },
    category: 'Paddy',
    pricePerKg: 225.00,
    change: 'up',
    changePercentage: 4.2,
    yesterdayPrice: 216.00,
    district: 'Anuradhapura',
    trendData: [210, 212, 215, 216, 225]
  },
  {
    id: 'price-2',
    cropName: { en: 'Nadu Paddy', si: 'නාඩු වී', ta: 'நாடு நெல்' },
    category: 'Paddy',
    pricePerKg: 195.00,
    change: 'stable',
    changePercentage: 0,
    yesterdayPrice: 195.00,
    district: 'Polonnaruwa',
    trendData: [192, 194, 195, 195, 195]
  },
  {
    id: 'price-3',
    cropName: { en: 'Red Onions (Local)', si: 'දේශීය රතු ළූණු', ta: 'உள்ளூர் சிவப்பு வெங்காயம்' },
    category: 'Vegetable',
    pricePerKg: 380.00,
    change: 'up',
    changePercentage: 8.5,
    yesterdayPrice: 350.00,
    district: 'Jaffna',
    trendData: [340, 342, 348, 350, 380]
  },
  {
    id: 'price-4',
    cropName: { en: 'Carrots', si: 'කැරට්', ta: 'கேரட்' },
    category: 'Vegetable',
    pricePerKg: 290.00,
    change: 'down',
    changePercentage: -5.3,
    yesterdayPrice: 306.00,
    district: 'Nuwara Eliya',
    trendData: [320, 315, 310, 306, 290]
  },
  {
    id: 'price-5',
    cropName: { en: 'Green Chillies', si: 'අමු මිරිස්', ta: 'பச்சை மிளகாய்' },
    category: 'Vegetable',
    pricePerKg: 420.00,
    change: 'up',
    changePercentage: 12.1,
    yesterdayPrice: 374.50,
    district: 'Dambulla (Matale)',
    trendData: [350, 360, 370, 374, 420]
  },
  {
    id: 'price-6',
    cropName: { en: 'Coconut (Large)', si: 'පොල් (විශාල)', ta: 'தேங்காய் (பெரியது)' },
    category: 'Coconut',
    pricePerKg: 120.00, // Per nut
    change: 'stable',
    changePercentage: 0.8,
    yesterdayPrice: 119.00,
    district: 'Kurunegala',
    trendData: [118, 118, 119, 119, 120]
  },
  {
    id: 'price-7',
    cropName: { en: 'Ceylon Black Pepper', si: 'ගම්මිරිස්', ta: 'கருப்பு மிளகு' },
    category: 'Spice',
    pricePerKg: 1650.00,
    change: 'up',
    changePercentage: 2.5,
    yesterdayPrice: 1610.00,
    district: 'Matale',
    trendData: [1580, 1600, 1605, 1610, 1650]
  }
];

export const MOCK_MARKETPLACE: MarketplaceItem[] = [
  {
    id: 'item-1',
    title: 'Freshly Harvested Organic Samba Paddy Rice',
    category: 'Produce',
    price: 210,
    unit: 'kg',
    quantityAvailable: 1500,
    sellerName: 'Gunapala Gamage',
    sellerRole: 'Farmer',
    sellerPhone: '+94 77 447 0098',
    location: 'Baddegama',
    district: 'Galle',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
    dateAdded: '2026-06-26'
  }
];

export const MOCK_WEATHER: Record<string, WeatherData> = {
  Anuradhapura: {
    temp: 33,
    condition: 'Sunny',
    humidity: 58,
    windSpeed: 14,
    rainProbability: 10,
    district: 'Anuradhapura',
    forecast: [
      { day: 'Sat', temp: 33, condition: 'Sunny' },
      { day: 'Sun', temp: 34, condition: 'Sunny' },
      { day: 'Mon', temp: 32, condition: 'Cloudy' },
      { day: 'Tue', temp: 31, condition: 'Rainy' },
      { day: 'Wed', temp: 33, condition: 'Sunny' },
    ]
  },
  'Nuwara Eliya': {
    temp: 18,
    condition: 'Rainy',
    humidity: 88,
    windSpeed: 18,
    rainProbability: 80,
    district: 'Nuwara Eliya',
    forecast: [
      { day: 'Sat', temp: 18, condition: 'Rainy' },
      { day: 'Sun', temp: 17, condition: 'Thunderstorm' },
      { day: 'Mon', temp: 19, condition: 'Cloudy' },
      { day: 'Tue', temp: 18, condition: 'Rainy' },
      { day: 'Wed', temp: 20, condition: 'Cloudy' },
    ]
  },
  Galle: {
    temp: 29,
    condition: 'Cloudy',
    humidity: 78,
    windSpeed: 12,
    rainProbability: 40,
    district: 'Galle',
    forecast: [
      { day: 'Sat', temp: 29, condition: 'Cloudy' },
      { day: 'Sun', temp: 30, condition: 'Sunny' },
      { day: 'Mon', temp: 28, condition: 'Rainy' },
      { day: 'Tue', temp: 29, condition: 'Cloudy' },
      { day: 'Wed', temp: 30, condition: 'Sunny' },
    ]
  },
  Kurunegala: {
    temp: 31,
    condition: 'Sunny',
    humidity: 65,
    windSpeed: 10,
    rainProbability: 15,
    district: 'Kurunegala',
    forecast: [
      { day: 'Sat', temp: 31, condition: 'Sunny' },
      { day: 'Sun', temp: 32, condition: 'Sunny' },
      { day: 'Mon', temp: 31, condition: 'Cloudy' },
      { day: 'Tue', temp: 30, condition: 'Rainy' },
      { day: 'Wed', temp: 31, condition: 'Sunny' },
    ]
  }
};

export const DEFAULT_WEATHER: WeatherData = {
  temp: 31,
  condition: 'Sunny',
  humidity: 62,
  windSpeed: 11,
  rainProbability: 20,
  district: 'Colombo',
  forecast: [
    { day: 'Sat', temp: 31, condition: 'Sunny' },
    { day: 'Sun', temp: 32, condition: 'Cloudy' },
    { day: 'Mon', temp: 30, condition: 'Rainy' },
    { day: 'Tue', temp: 31, condition: 'Sunny' },
    { day: 'Wed', temp: 31, condition: 'Sunny' },
  ]
};

export const CHAT_KNOWLEDGE_BASE = [
  {
    keywords: ['paddy', 'rice', 'samba', 'වී', 'நெல்'],
    response: "For Paddy farming in Sri Lanka, make sure you keep the water levels at 2-5cm during the transplanting and vegetative phases, but drain it completely 10 days before harvesting. For organic nitrogen, try incorporating Gliricidia sepium (වැටහිරියා) leaves into your soil, which boosts yield significantly. Do you have a specific variety like Bg 300 or Keeri Samba?"
  },
  {
    keywords: ['fertilizer', 'urea', 'organic', 'පොහොර', 'உரம்'],
    response: "Sri Lanka's Department of Agriculture recommends a balanced application. If you are applying Urea, combine it with organic compost to prevent nitrogen leaching. Under the National Organic Fertilizer Subsidy, you can get free compost and a cash subsidy. Try our integrated 'Fertilizer Calculator' in the sidebar to compute exact soil NPK requirements based on your land size!"
  },
  {
    keywords: ['onion', 'red onion', 'ළූණු', 'வெங்காயம்'],
    response: "Red onions grow exceptionally well in Jaffna, Vavuniya, and Kalpitiya sandy loams. Keep soil pH between 6.0 and 7.0. Beware of Purple Blotch disease during high humidity; you can manage it with healthy drainage and applying neem-based bio-pesticides. Harvest when 70-80% of tops have fallen over."
  },
  {
    keywords: ['pest', 'insects', 'thrips', 'worms', 'පළිබෝධ', 'பூச்சி'],
    response: "For eco-friendly pest control in Sri Lanka: \n1. Leaf folder / stem borer: Set up light traps in the field.\n2. Thrips (common in Green Chilli/Onion): Spray neem seed kernel extract (NSKE 5%) or tobacco extract.\n3. Keep natural predators active by planting companion flowering herbs around bunds."
  },
  {
    keywords: ['subsidy', 'scheme', 'government', 'සහනාධාර', 'மானியம்'],
    response: "Currently open national schemes: \n- Organic Paddy Fertilizer subsidy (85% subsidized + cash grants).\n- Agri-Tech Smart Micro-Irrigation Grant (70% subsidy for drip/sprinkler units in Dry Zone districts).\nApply today via our 'Subsidies & Schemes' portal; we'll automatically prepare your digital Gov-Form!"
  },
  {
    keywords: ['cinnamon', 'export', 'කුරුඳු', 'இலவங்கப்பட்டை'],
    response: "Sri Lanka produces 85% of the world's pure Ceylon Cinnamon (Alba, C5, M5, H1 grades). Cinnamon thrives in acidic sandy soils of southern wet zones (Galle, Matara). Prune shoots when stems turn brown. Scraping and rolling must be done early in the morning when the bark is moist."
  }
];

export const GENERAL_BOT_REPLIES = [
  "Ayubowan! I am your Sarunena Smart Agri Advisor. Tell me which crop you are planting or if you'd like advice on local weather, fertilizer ratios, or crop prices.",
  "That is an interesting topic! In Sri Lanka, agricultural success depends greatly on matching your crop with the right zone (Wet Zone, Dry Zone, Intermediate Zone). Which district is your farm located in?",
  "To give you the most accurate advice, please let me know your soil type (e.g., sandy loam, red-yellow podzolic) and current crop growth stage.",
  "You can also use our specialized Fertilizer Calculator tool to get personalized soil recommendation sheets certified by agricultural officers."
];
